### ISSUE TITLE
Error thrown in 0.3.5 if composer.json is not present

### ISSUE THREAD

**Issue by brentsowers1** [swarajban/npm-cache#14]
With the 0.3.5 release last night my npm-cache installs are all failing (exit code 1) with this error:
```
[npm-cache] [INFO] [bower] Dependency config file {my code directory}/bower.json does not exist. Skipping install
module.js:338
    throw err;
          ^
Error: Cannot find module '{my code directory}/composer.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ({my code directory}/node_modules/npm-cache/cacheDependencyManagers/composerConfig.js:27:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

0.3.4 does not have this issue, I do not need composer.json and bower.json to be present to run npm-cache install.

**Comment by swarajban** [comment]
ah damn, ok will fix today... didn't test this case in pr

**Comment by etiennetremel** [comment]
@swarajban any updates on this?

**Comment by swarajban** [comment]
Fixed! Grab 0.3.6 from npm

**Comment by swarajban** [comment]
Sorry for delay...

**Comment by etiennetremel** [comment]
cool, thank you!
