### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by babbelnedd** [swarajban/npm-cache#28]
###packages.json

```
{
     // ...
    "devDependencies": {
        "beepbeep": "^1.2.0",
        "browser-sync": "^2.10.0",
        "gulp-autoprefixer": "^3.1.0",
        "gulp-concat": "^2.6.0",
        "gulp-html-minifier": "^0.1.6",
        "gulp-imagemin": "^2.4.0",
        "gulp-less": "^3.0.5",
        "gulp-rename": "^1.2.2",
        "gulp-sourcemaps": "^1.6.0",
        "gulp-tslint": "^4.1.0",
        "gulp-typescript": "^2.9.2",
        "gulp-uglify": "^1.5.1",
        "gulp-uncss": "^1.0.4",
        "gulp-util": "^3.0.7",
        "imagemin-pngquant": "^4.2.0",
        "less-plugin-clean-css": "^1.5.1",
        "merge2": "^0.3.6",
        "tslint": "^3.1.1"
    }
}
``` 

gulp is globally installed

requiring `gulp-less` ends in the following error. default npm install works fine

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/www/xxx/builds/835110e/src/node_modules/gulp-less/node_modules/accord/lib/index.js:11:7)
    at Object.<anonymous> (/var/www/xxx/builds/835110e/src/node_modules/gulp-less/node_modules/accord/lib/index.js:100:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
````

**Comment by babbelnedd** [comment]
Hmmm.. cleaning cache and loading deps again fixed it for now. I'll keep an eye on it :/

**Comment by babbelnedd** [comment]
Well I guess there were some kind of bug while initializing the cache, dunno :/
Anyway, the last ~20 deploys (tested a lot :grin:) were all fine. Reduced my deploy time from ~20minutes to ~30seconds. :grinning:
