### ISSUE TITLE
Failing to clear installed dependencies

### ISSUE THREAD

**Issue by AStoker** [swarajban/npm-cache#43]
Trying to run the `npm-cache` command back to back results in an error coming up from RimRaf saying that a directory is not empty. 
```
>npm-cache install --cacheDirectory "C:\Users\Andrew Stoker\AppData\Roaming\npm-cache" npm
[npm-cache] [INFO] using C:\Users\Andrew Stoker\AppData\Roaming\npm-cache as cache directory
[npm-cache] [INFO] [npm] config file exists
[npm-cache] [INFO] [npm] cli exists
[npm-cache] [INFO] [npm] hash of C:\Workflow\Branches\CentralPrototype\Projects\Source\WebApplication\package.json: bf9c78e40ae0c10c7636ed4d576043fa
[npm-cache] [INFO] [npm] cache exists
[npm-cache] [INFO] [npm] clearing installed dependencies at C:\Workflow\Branches\CentralPrototype\Projects\Source\WebApplication\node_modules
C:\Users\Andrew Stoker\AppData\Roaming\npm\node_modules\npm-cache\node_modules\rimraf\rimraf.js:304
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Workflow\Branches\CentralPrototype\Projects\Source\WebApplication\node_modules\bower-installer\node_modules\glob'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:806:18)
    at rmkidsSync (C:\Users\Andrew Stoker\AppData\Roaming\npm\node_modules\npm-cache\node_modules\rimraf\rimraf.js:334:11)
    at rmdirSync (C:\Users\Andrew Stoker\AppData\Roaming\npm\node_modules\npm-cache\node_modules\rimraf\rimraf.js:324:7)
    at rimrafSync (C:\Users\Andrew Stoker\AppData\Roaming\npm\node_modules\npm-cache\node_modules\rimraf\rimraf.js:295:9)
    at C:\Users\Andrew Stoker\AppData\Roaming\npm\node_modules\npm-cache\node_modules\rimraf\rimraf.js:332:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Andrew Stoker\AppData\Roaming\npm\node_modules\npm-cache\node_modules\rimraf\rimraf.js:331:26)
    at rmdirSync (C:\Users\Andrew Stoker\AppData\Roaming\npm\node_modules\npm-cache\node_modules\rimraf\rimraf.js:324:7)
    at rimrafSync (C:\Users\Andrew Stoker\AppData\Roaming\npm\node_modules\npm-cache\node_modules\rimraf\rimraf.js:295:9)
```

Running v. 0.5.3 of npm-cache.

**Comment by swarajban** [comment]
Hm strange, not seeing this on mac. I don't have a windows box till the end of week, but will check it out then. If you have time to submit a PR, I'm happy to merge it in

**Comment by AStoker** [comment]
My setup is a mac with windows as a virtual machine. I did have the whole solution on a shared drive between the mac and pc, but when I got this error I tried it on just the pc drive (same result). I'm not sure of the cause of the issue yet...

**Comment by sod** [comment]
Ticket https://github.com/isaacs/rimraf/issues/25 lists some possible issues

* anti virus program locks files while scanning
* another process is writing into node_modules
* another process locks files (node webserver running?)
* cmd.exe is open and navigated inside node_modules
* bug in libuv (update nodejs)

**Comment by swarajban** [comment]
Is this still happening?

**Comment by AStoker** [comment]
Yes this is still happening. I'm now running Node v5.5.0, and npm-cache v0.6.0. I doubt it's an antivirus program locking the files, because any other kind of delete in the power shell operates as expected. I don't have any other processes that I can find that are writing into the node_modules folder. I don't have a node web server running, or any other kind of node process looking at it. I'm running powershell instead of cmd.exe, and it's not inside node modules folder (however, testing with cmd.exe does the same thing). 

Sorry about the delay in response.

**Comment by swarajban** [comment]
No worries, will look into this next. Sorry this has been happening!

**Comment by damountie** [comment]
Was there any progress? I'm finding that this is still happening. However, I'm also finding that running it _again_ will resolve the issue.

Still, not ideal. When it _does_ fail, it is consistently for `rimraf`, see OP.
