### ISSUE TITLE
When calling npm-cache from a Node.js exec, if NPM_CACHE_DIR isn't set, an exception is thrown.

### ISSUE THREAD

**Issue by SteffanDonal** [swarajban/npm-cache#51]
Hi!

I'm using npm-cache as part of my deployment system, and found that if NPM_CACHE_DIR isn't set on the environment when called from `child_process.exec`, it throws the following exception:
```
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at main (/usr/lib/node_modules/npm-cache/index.js:36:48)
    at Object.<anonymous> (/usr/lib/node_modules/npm-cache/index.js:159:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

I did the following to prevent this error: `export NPM_CACHE_DIR=/path/to/cache && npm-cache install`

Note: this happened even when specifying the cache directory through the `cacheDirectory` or `c` parameters.

**Comment by swarajban** [comment]
Fixed in `0.6.3`
